const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const sdl = b.addStaticLibrary(.{
        .name = "SDL2",
        .target = target,
        .optimize = optimize,
    });

    const sdl_ttf = b.addStaticLibrary(.{
        .name = "SDL2_ttf",
        .target = target,
        // had some weird issues with debugging when building this in debug mode
        .optimize = .ReleaseFast,
    });

    const sdl_img = b.addStaticLibrary(.{
        .name = "SDL_image",
        .target = target,
        .optimize = optimize,
    });

    const t = target.os_tag orelse sdl.target_info.target.os.tag;

    sdl.addIncludePath(.{ .path = "SDL/include" });
    sdl_ttf.addIncludePath(.{ .path = "SDL/include" });
    sdl_img.addIncludePath(.{ .path = "SDL/include" });

    sdl_ttf.addIncludePath(.{ .path = "SDL_ttf/include" });
    sdl_img.addIncludePath(.{ .path = "SDL_img/include" });

    sdl.linkLibC();
    sdl_ttf.linkLibC();
    sdl_img.linkLibC();

    switch (t) {
        .windows => {
            sdl.addCSourceFiles(&windows_src_files, &.{});
            sdl.linkSystemLibrary("setupapi");
            sdl.linkSystemLibrary("winmm");
            sdl.linkSystemLibrary("gdi32");
            sdl.linkSystemLibrary("imm32");
            sdl.linkSystemLibrary("version");
            sdl.linkSystemLibrary("oleaut32");
            sdl.linkSystemLibrary("ole32");
        },
        .macos => {
            sdl.addCSourceFiles(&darwin_src_files, &.{});
            sdl.addCSourceFiles(&objective_c_src_files, &.{"-fobjc-arc"});
            sdl.linkFramework("OpenGL");
            sdl.linkFramework("Metal");
            sdl.linkFramework("CoreVideo");
            sdl.linkFramework("Cocoa");
            sdl.linkFramework("IOKit");
            sdl.linkFramework("ForceFeedback");
            sdl.linkFramework("Carbon");
            sdl.linkFramework("CoreAudio");
            sdl.linkFramework("AudioToolbox");
            sdl.linkFramework("AVFoundation");
            sdl.linkFramework("Foundation");
        },
        else => {
            sdl.addIncludePath(.{ .cwd_relative = "/usr/include/libdecor-0" });
            sdl.addIncludePath(.{ .cwd_relative = "/usr/include/dbus-1.0" });
            sdl.addIncludePath(.{ .cwd_relative = "/usr/lib/dbus-1.0/include" });
            sdl.addIncludePath(.{ .cwd_relative = "/usr/lib/x86_64-linux-gnu/dbus-1.0/include" });
            sdl.addIncludePath(.{ .cwd_relative = "/usr/include/pipewire-0.3" });
            sdl.addIncludePath(.{ .cwd_relative = "/usr/include/spa-0.2" });
            sdl.addIncludePath(.{ .cwd_relative = "/usr/include/libdrm" });
            sdl.addIncludePath(.{ .path = "SDL/wayland-generated-protocols" });
            sdl.addCSourceFiles(&linux_src_files, &.{});
            sdl.addCSourceFiles(&wayland_src_files, &.{});
            const config_header = b.addConfigHeader(.{
                .style = .{ .blank = {} },
                .include_path = "SDL_config_linux.h",
            }, linux_config_h_vals);
            sdl.addConfigHeader(config_header);
            sdl_ttf.addConfigHeader(config_header);
            sdl.step.dependOn(&config_header.step);
            sdl_ttf.step.dependOn(&config_header.step);
        },
    }

    sdl.addCSourceFiles(&generic_sdl_src_files, &.{});
    sdl.defineCMacro("SDL_USE_BUILTIN_OPENGL_DEFINITIONS", "1");

    sdl_ttf.addCSourceFile(.{ .file = .{ .path = "SDL_ttf/SDL_ttf.c" }, .flags = &.{} });
    sdl_ttf.linkSystemLibrary("freetype2");
    sdl_ttf.linkSystemLibrary("harfbuzz");

    sdl_img.addCSourceFiles(&img_src_files, &.{});
    sdl_img.defineCMacro("LOAD_PNG", "1");
    sdl_img.linkSystemLibrary("libpng16");

    b.installArtifact(sdl);
    b.installArtifact(sdl_ttf);
    b.installArtifact(sdl_img);
}

const img_src_files = .{
    "SDL_img/IMG.c",
    "SDL_img/IMG_ImageIO.m",
    "SDL_img/IMG_WIC.c",
    "SDL_img/IMG_avif.c",
    "SDL_img/IMG_bmp.c",
    "SDL_img/IMG_gif.c",
    "SDL_img/IMG_jpg.c",
    "SDL_img/IMG_jxl.c",
    "SDL_img/IMG_lbm.c",
    "SDL_img/IMG_pcx.c",
    "SDL_img/IMG_png.c",
    "SDL_img/IMG_pnm.c",
    "SDL_img/IMG_qoi.c",
    "SDL_img/IMG_stb.c",
    "SDL_img/IMG_svg.c",
    "SDL_img/IMG_tga.c",
    "SDL_img/IMG_tif.c",
    "SDL_img/IMG_webp.c",
    "SDL_img/IMG_xcf.c",
    "SDL_img/IMG_xpm.c",
    "SDL_img/IMG_xv.c",
};

const generic_sdl_src_files = [_][]const u8{
    "SDL/src/SDL.c",
    "SDL/src/SDL_assert.c",
    "SDL/src/SDL_dataqueue.c",
    "SDL/src/SDL_error.c",
    "SDL/src/SDL_guid.c",
    "SDL/src/SDL_hints.c",
    "SDL/src/SDL_list.c",
    "SDL/src/SDL_log.c",
    "SDL/src/SDL_utils.c",
    "SDL/src/atomic/SDL_atomic.c",
    "SDL/src/atomic/SDL_spinlock.c",
    "SDL/src/audio/SDL_audio.c",
    "SDL/src/audio/SDL_audiocvt.c",
    "SDL/src/audio/SDL_audiodev.c",
    "SDL/src/audio/SDL_audiotypecvt.c",
    "SDL/src/audio/SDL_mixer.c",
    "SDL/src/audio/SDL_wave.c",
    "SDL/src/cpuinfo/SDL_cpuinfo.c",
    "SDL/src/dynapi/SDL_dynapi.c",
    "SDL/src/events/SDL_clipboardevents.c",
    "SDL/src/events/SDL_displayevents.c",
    "SDL/src/events/SDL_dropevents.c",
    "SDL/src/events/SDL_events.c",
    "SDL/src/events/SDL_gesture.c",
    "SDL/src/events/SDL_keyboard.c",
    "SDL/src/events/SDL_keysym_to_scancode.c",
    "SDL/src/events/SDL_mouse.c",
    "SDL/src/events/SDL_quit.c",
    "SDL/src/events/SDL_scancode_tables.c",
    "SDL/src/events/SDL_touch.c",
    "SDL/src/events/SDL_windowevents.c",
    "SDL/src/events/imKStoUCS.c",
    "SDL/src/file/SDL_rwops.c",
    "SDL/src/haptic/SDL_haptic.c",
    "SDL/src/hidapi/SDL_hidapi.c",

    "SDL/src/joystick/SDL_gamecontroller.c",
    "SDL/src/joystick/SDL_joystick.c",
    "SDL/src/joystick/controller_type.c",
    "SDL/src/joystick/virtual/SDL_virtualjoystick.c",

    "SDL/src/libm/e_atan2.c",
    "SDL/src/libm/e_exp.c",
    "SDL/src/libm/e_fmod.c",
    "SDL/src/libm/e_log.c",
    "SDL/src/libm/e_log10.c",
    "SDL/src/libm/e_pow.c",
    "SDL/src/libm/e_rem_pio2.c",
    "SDL/src/libm/e_sqrt.c",
    "SDL/src/libm/k_cos.c",
    "SDL/src/libm/k_rem_pio2.c",
    "SDL/src/libm/k_sin.c",
    "SDL/src/libm/k_tan.c",
    "SDL/src/libm/s_atan.c",
    "SDL/src/libm/s_copysign.c",
    "SDL/src/libm/s_cos.c",
    "SDL/src/libm/s_fabs.c",
    "SDL/src/libm/s_floor.c",
    "SDL/src/libm/s_scalbn.c",
    "SDL/src/libm/s_sin.c",
    "SDL/src/libm/s_tan.c",
    "SDL/src/locale/SDL_locale.c",
    "SDL/src/misc/SDL_url.c",
    "SDL/src/power/SDL_power.c",
    "SDL/src/render/SDL_d3dmath.c",
    "SDL/src/render/SDL_render.c",
    "SDL/src/render/SDL_yuv_sw.c",
    "SDL/src/sensor/SDL_sensor.c",
    "SDL/src/stdlib/SDL_crc16.c",
    "SDL/src/stdlib/SDL_crc32.c",
    "SDL/src/stdlib/SDL_getenv.c",
    "SDL/src/stdlib/SDL_iconv.c",
    "SDL/src/stdlib/SDL_malloc.c",
    "SDL/src/stdlib/SDL_mslibc.c",
    "SDL/src/stdlib/SDL_qsort.c",
    "SDL/src/stdlib/SDL_stdlib.c",
    "SDL/src/stdlib/SDL_string.c",
    "SDL/src/stdlib/SDL_strtokr.c",
    "SDL/src/thread/SDL_thread.c",
    "SDL/src/timer/SDL_timer.c",
    "SDL/src/video/SDL_RLEaccel.c",
    "SDL/src/video/SDL_blit.c",
    "SDL/src/video/SDL_blit_0.c",
    "SDL/src/video/SDL_blit_1.c",
    "SDL/src/video/SDL_blit_A.c",
    "SDL/src/video/SDL_blit_N.c",
    "SDL/src/video/SDL_blit_auto.c",
    "SDL/src/video/SDL_blit_copy.c",
    "SDL/src/video/SDL_blit_slow.c",
    "SDL/src/video/SDL_bmp.c",
    "SDL/src/video/SDL_clipboard.c",
    "SDL/src/video/SDL_egl.c",
    "SDL/src/video/SDL_fillrect.c",
    "SDL/src/video/SDL_pixels.c",
    "SDL/src/video/SDL_rect.c",
    "SDL/src/video/SDL_shape.c",
    "SDL/src/video/SDL_stretch.c",
    "SDL/src/video/SDL_surface.c",
    "SDL/src/video/SDL_video.c",
    "SDL/src/video/SDL_vulkan_utils.c",
    "SDL/src/video/SDL_yuv.c",
    "SDL/src/video/yuv2rgb/yuv_rgb.c",

    "SDL/src/video/dummy/SDL_nullevents.c",
    "SDL/src/video/dummy/SDL_nullframebuffer.c",
    "SDL/src/video/dummy/SDL_nullvideo.c",

    "SDL/src/render/software/SDL_blendfillrect.c",
    "SDL/src/render/software/SDL_blendline.c",
    "SDL/src/render/software/SDL_blendpoint.c",
    "SDL/src/render/software/SDL_drawline.c",
    "SDL/src/render/software/SDL_drawpoint.c",
    "SDL/src/render/software/SDL_render_sw.c",
    "SDL/src/render/software/SDL_rotate.c",
    "SDL/src/render/software/SDL_triangle.c",

    "SDL/src/audio/dummy/SDL_dummyaudio.c",

    "SDL/src/joystick/hidapi/SDL_hidapi_combined.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_gamecube.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_luna.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_ps3.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_ps4.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_ps5.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_rumble.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_shield.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_stadia.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_steam.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_switch.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_wii.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_xbox360.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_xbox360w.c",
    "SDL/src/joystick/hidapi/SDL_hidapi_xboxone.c",
    "SDL/src/joystick/hidapi/SDL_hidapijoystick.c",
};

const windows_src_files = [_][]const u8{
    "SDL/src/core/windows/SDL_hid.c",
    "SDL/src/core/windows/SDL_immdevice.c",
    "SDL/src/core/windows/SDL_windows.c",
    "SDL/src/core/windows/SDL_xinput.c",
    "SDL/src/filesystem/windows/SDL_sysfilesystem.c",
    "SDL/src/haptic/windows/SDL_dinputhaptic.c",
    "SDL/src/haptic/windows/SDL_windowshaptic.c",
    "SDL/src/haptic/windows/SDL_xinputhaptic.c",
    "SDL/src/hidapi/windows/hid.c",
    "SDL/src/joystick/windows/SDL_dinputjoystick.c",
    "SDL/src/joystick/windows/SDL_rawinputjoystick.c",
    // This can be enabled when Zig updates to the next mingw-w64 release,
    // which will make the headers gain `windows.gaming.input.h`.
    // Also revert the patch 2c79fd8fd04f1e5045cbe5978943b0aea7593110.
    //"src/joystick/windows/SDL_windows_gaming_input.c",
    "SDL/src/joystick/windows/SDL_windowsjoystick.c",
    "SDL/src/joystick/windows/SDL_xinputjoystick.c",

    "SDL/src/loadso/windows/SDL_sysloadso.c",
    "SDL/src/locale/windows/SDL_syslocale.c",
    "SDL/src/main/windows/SDL_windows_main.c",
    "SDL/src/misc/windows/SDL_sysurl.c",
    "SDL/src/power/windows/SDL_syspower.c",
    "SDL/src/sensor/windows/SDL_windowssensor.c",
    "SDL/src/timer/windows/SDL_systimer.c",
    "SDL/src/video/windows/SDL_windowsclipboard.c",
    "SDL/src/video/windows/SDL_windowsevents.c",
    "SDL/src/video/windows/SDL_windowsframebuffer.c",
    "SDL/src/video/windows/SDL_windowskeyboard.c",
    "SDL/src/video/windows/SDL_windowsmessagebox.c",
    "SDL/src/video/windows/SDL_windowsmodes.c",
    "SDL/src/video/windows/SDL_windowsmouse.c",
    "SDL/src/video/windows/SDL_windowsopengl.c",
    "SDL/src/video/windows/SDL_windowsopengles.c",
    "SDL/src/video/windows/SDL_windowsshape.c",
    "SDL/src/video/windows/SDL_windowsvideo.c",
    "SDL/src/video/windows/SDL_windowsvulkan.c",
    "SDL/src/video/windows/SDL_windowswindow.c",

    "SDL/src/thread/windows/SDL_syscond_cv.c",
    "SDL/src/thread/windows/SDL_sysmutex.c",
    "SDL/src/thread/windows/SDL_syssem.c",
    "SDL/src/thread/windows/SDL_systhread.c",
    "SDL/src/thread/windows/SDL_systls.c",
    "SDL/src/thread/generic/SDL_syscond.c",

    "SDL/src/render/direct3d/SDL_render_d3d.c",
    "SDL/src/render/direct3d/SDL_shaders_d3d.c",
    "SDL/src/render/direct3d11/SDL_render_d3d11.c",
    "SDL/src/render/direct3d11/SDL_shaders_d3d11.c",
    "SDL/src/render/direct3d12/SDL_render_d3d12.c",
    "SDL/src/render/direct3d12/SDL_shaders_d3d12.c",

    "SDL/src/audio/directsound/SDL_directsound.c",
    "SDL/src/audio/wasapi/SDL_wasapi.c",
    "SDL/src/audio/wasapi/SDL_wasapi_win32.c",
    "SDL/src/audio/winmm/SDL_winmm.c",
    "SDL/src/audio/disk/SDL_diskaudio.c",

    "SDL/src/render/opengl/SDL_render_gl.c",
    "SDL/src/render/opengl/SDL_shaders_gl.c",
    "SDL/src/render/opengles/SDL_render_gles.c",
    "SDL/src/render/opengles2/SDL_render_gles2.c",
    "SDL/src/render/opengles2/SDL_shaders_gles2.c",
};

const linux_src_files = [_][]const u8{
    "SDL/src/timer/unix/SDL_systimer.c",
    "SDL/src/loadso/dlopen/SDL_sysloadso.c",
    "SDL/src/core/linux/SDL_dbus.c",
    "SDL/src/core/linux/SDL_evdev.c",
    "SDL/src/core/linux/SDL_evdev_capabilities.c",
    "SDL/src/core/linux/SDL_evdev_kbd.c",
    // "src/core/linux/SDL_fcitx.c",
    "SDL/src/core/linux/SDL_ibus.c",
    "SDL/src/core/linux/SDL_ime.c",
    "SDL/src/core/linux/SDL_sandbox.c",
    "SDL/src/core/linux/SDL_threadprio.c",
    "SDL/src/core/linux/SDL_udev.c",
    "SDL/src/haptic/linux/SDL_syshaptic.c",
    "SDL/src/hidapi/linux/hid.c",
    "SDL/src/joystick/linux/SDL_sysjoystick.c",
    "SDL/src/joystick/steam/SDL_steamcontroller.c",
    "SDL/src/power/linux/SDL_syspower.c",

    "SDL/src/video/wayland/SDL_waylandclipboard.c",
    "SDL/src/video/wayland/SDL_waylanddatamanager.c",
    "SDL/src/video/wayland/SDL_waylanddyn.c",
    "SDL/src/video/wayland/SDL_waylandevents.c",
    "SDL/src/video/wayland/SDL_waylandkeyboard.c",
    "SDL/src/video/wayland/SDL_waylandmessagebox.c",
    "SDL/src/video/wayland/SDL_waylandmouse.c",
    "SDL/src/video/wayland/SDL_waylandopengles.c",
    "SDL/src/video/wayland/SDL_waylandtouch.c",
    "SDL/src/video/wayland/SDL_waylandvideo.c",
    "SDL/src/video/wayland/SDL_waylandvulkan.c",
    "SDL/src/video/wayland/SDL_waylandwindow.c",

    "SDL/src/video/x11/SDL_x11clipboard.c",
    "SDL/src/video/x11/SDL_x11dyn.c",
    "SDL/src/video/x11/SDL_x11events.c",
    "SDL/src/video/x11/SDL_x11framebuffer.c",
    "SDL/src/video/x11/SDL_x11keyboard.c",
    "SDL/src/video/x11/SDL_x11messagebox.c",
    "SDL/src/video/x11/SDL_x11modes.c",
    "SDL/src/video/x11/SDL_x11mouse.c",
    "SDL/src/video/x11/SDL_x11opengl.c",
    "SDL/src/video/x11/SDL_x11opengles.c",
    "SDL/src/video/x11/SDL_x11shape.c",
    "SDL/src/video/x11/SDL_x11touch.c",
    "SDL/src/video/x11/SDL_x11video.c",
    "SDL/src/video/x11/SDL_x11vulkan.c",
    "SDL/src/video/x11/SDL_x11window.c",
    "SDL/src/video/x11/SDL_x11xfixes.c",
    "SDL/src/video/x11/SDL_x11xinput2.c",
    "SDL/src/video/x11/edid-parse.c",

    "SDL/src/audio/alsa/SDL_alsa_audio.c",
    "SDL/src/audio/jack/SDL_jackaudio.c",
    "SDL/src/audio/pulseaudio/SDL_pulseaudio.c",
    "SDL/src/audio/pipewire/SDL_pipewire.c",
    "SDL/src/audio/dsp/SDL_dspaudio.c",
    "SDL/src/audio/disk/SDL_diskaudio.c",

    "SDL/src/thread/pthread/SDL_syscond.c",
    "SDL/src/thread/pthread/SDL_sysmutex.c",
    "SDL/src/thread/pthread/SDL_syssem.c",
    "SDL/src/thread/pthread/SDL_systhread.c",
    "SDL/src/thread/pthread/SDL_systls.c",
    "SDL/src/core/unix/SDL_poll.c",

    "SDL/src/misc/SDL_url.c",
    "SDL/src/misc/unix/SDL_sysurl.c",
    "SDL/src/sensor/dummy/SDL_dummysensor.c",
    "SDL/src/sensor/SDL_sensor.c",
    "SDL/src/render/opengl/SDL_render_gl.c",
    "SDL/src/render/opengl/SDL_shaders_gl.c",
    "SDL/src/render/opengles2/SDL_render_gles2.c",
    "SDL/src/render/opengles2/SDL_shaders_gles2.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmdyn.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmevents.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmmouse.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmopengles.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmvideo.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmvulkan.c",
    "SDL/src/video/offscreen/SDL_offscreenevents.c",
    "SDL/src/video/offscreen/SDL_offscreenframebuffer.c",
    "SDL/src/video/offscreen/SDL_offscreenopengles.c",
    "SDL/src/video/offscreen/SDL_offscreenvideo.c",
    "SDL/src/video/offscreen/SDL_offscreenwindow.c",
};

const darwin_src_files = [_][]const u8{
    "SDL/src/haptic/darwin/SDL_syshaptic.c",
    "SDL/src/joystick/darwin/SDL_iokitjoystick.c",
    "SDL/src/power/macosx/SDL_syspower.c",
    "SDL/src/timer/unix/SDL_systimer.c",
    "SDL/src/loadso/dlopen/SDL_sysloadso.c",
    "SDL/src/audio/disk/SDL_diskaudio.c",
    "SDL/src/render/opengl/SDL_render_gl.c",
    "SDL/src/render/opengl/SDL_shaders_gl.c",
    "SDL/src/render/opengles/SDL_render_gles.c",
    "SDL/src/render/opengles2/SDL_render_gles2.c",
    "SDL/src/render/opengles2/SDL_shaders_gles2.c",
    "SDL/src/sensor/dummy/SDL_dummysensor.c",

    "SDL/src/thread/pthread/SDL_syscond.c",
    "SDL/src/thread/pthread/SDL_sysmutex.c",
    "SDL/src/thread/pthread/SDL_syssem.c",
    "SDL/src/thread/pthread/SDL_systhread.c",
    "SDL/src/thread/pthread/SDL_systls.c",
};

const objective_c_src_files = [_][]const u8{
    "SDL/src/audio/coreaudio/SDL_coreaudio.m",
    "SDL/src/file/cocoa/SDL_rwopsbundlesupport.m",
    "SDL/src/filesystem/cocoa/SDL_sysfilesystem.m",
    //"src/hidapi/testgui/mac_support_cocoa.m",
    // This appears to be for SDL3 only.
    //"src/joystick/apple/SDL_mfijoystick.m",
    "SDL/src/locale/macosx/SDL_syslocale.m",
    "SDL/src/misc/macosx/SDL_sysurl.m",
    "SDL/src/power/uikit/SDL_syspower.m",
    "SDL/src/render/metal/SDL_render_metal.m",
    "SDL/src/sensor/coremotion/SDL_coremotionsensor.m",
    "SDL/src/video/cocoa/SDL_cocoaclipboard.m",
    "SDL/src/video/cocoa/SDL_cocoaevents.m",
    "SDL/src/video/cocoa/SDL_cocoakeyboard.m",
    "SDL/src/video/cocoa/SDL_cocoamessagebox.m",
    "SDL/src/video/cocoa/SDL_cocoametalview.m",
    "SDL/src/video/cocoa/SDL_cocoamodes.m",
    "SDL/src/video/cocoa/SDL_cocoamouse.m",
    "SDL/src/video/cocoa/SDL_cocoaopengl.m",
    "SDL/src/video/cocoa/SDL_cocoaopengles.m",
    "SDL/src/video/cocoa/SDL_cocoashape.m",
    "SDL/src/video/cocoa/SDL_cocoavideo.m",
    "SDL/src/video/cocoa/SDL_cocoavulkan.m",
    "SDL/src/video/cocoa/SDL_cocoawindow.m",
    "SDL/src/video/uikit/SDL_uikitappdelegate.m",
    "SDL/src/video/uikit/SDL_uikitclipboard.m",
    "SDL/src/video/uikit/SDL_uikitevents.m",
    "SDL/src/video/uikit/SDL_uikitmessagebox.m",
    "SDL/src/video/uikit/SDL_uikitmetalview.m",
    "SDL/src/video/uikit/SDL_uikitmodes.m",
    "SDL/src/video/uikit/SDL_uikitopengles.m",
    "SDL/src/video/uikit/SDL_uikitopenglview.m",
    "SDL/src/video/uikit/SDL_uikitvideo.m",
    "SDL/src/video/uikit/SDL_uikitview.m",
    "SDL/src/video/uikit/SDL_uikitviewcontroller.m",
    "SDL/src/video/uikit/SDL_uikitvulkan.m",
    "SDL/src/video/uikit/SDL_uikitwindow.m",
};

const ios_src_files = [_][]const u8{
    "SDL/src/hidapi/ios/hid.m",
    "SDL/src/misc/ios/SDL_sysurl.m",
    "SDL/src/joystick/iphoneos/SDL_mfijoystick.m",
};

const wayland_src_files = [_][]const u8{
    "SDL/wayland-generated-protocols/idle-inhibit-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/keyboard-shortcuts-inhibit-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/pointer-constraints-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/primary-selection-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/relative-pointer-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/tablet-unstable-v2-protocol.c",
    "SDL/wayland-generated-protocols/text-input-unstable-v3-protocol.c",
    "SDL/wayland-generated-protocols/viewporter-protocol.c",
    "SDL/wayland-generated-protocols/wayland-protocol.c",
    "SDL/wayland-generated-protocols/xdg-activation-v1-protocol.c",
    "SDL/wayland-generated-protocols/xdg-decoration-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/xdg-output-unstable-v1-protocol.c",
    "SDL/wayland-generated-protocols/xdg-shell-protocol.c",
};

const unknown_src_files = [_][]const u8{
    "SDL/src/thread/generic/SDL_syscond.c",
    "SDL/src/thread/generic/SDL_sysmutex.c",
    "SDL/src/thread/generic/SDL_syssem.c",
    "SDL/src/thread/generic/SDL_systhread.c",
    "SDL/src/thread/generic/SDL_systls.c",

    "SDL/src/audio/aaudio/SDL_aaudio.c",
    "SDL/src/audio/android/SDL_androidaudio.c",
    "SDL/src/audio/arts/SDL_artsaudio.c",
    "SDL/src/audio/dsp/SDL_dspaudio.c",
    "SDL/src/audio/emscripten/SDL_emscriptenaudio.c",
    "SDL/src/audio/esd/SDL_esdaudio.c",
    "SDL/src/audio/fusionsound/SDL_fsaudio.c",
    "SDL/src/audio/n3ds/SDL_n3dsaudio.c",
    "SDL/src/audio/nacl/SDL_naclaudio.c",
    "SDL/src/audio/nas/SDL_nasaudio.c",
    "SDL/src/audio/netbsd/SDL_netbsdaudio.c",
    "SDL/src/audio/openslES/SDL_openslES.c",
    "SDL/src/audio/os2/SDL_os2audio.c",
    "SDL/src/audio/paudio/SDL_paudio.c",
    "SDL/src/audio/pipewire/SDL_pipewire.c",
    "SDL/src/audio/ps2/SDL_ps2audio.c",
    "SDL/src/audio/psp/SDL_pspaudio.c",
    "SDL/src/audio/qsa/SDL_qsa_audio.c",
    "SDL/src/audio/sndio/SDL_sndioaudio.c",
    "SDL/src/audio/sun/SDL_sunaudio.c",
    "SDL/src/audio/vita/SDL_vitaaudio.c",

    "SDL/src/core/android/SDL_android.c",
    "SDL/src/core/freebsd/SDL_evdev_kbd_freebsd.c",
    "SDL/src/core/openbsd/SDL_wscons_kbd.c",
    "SDL/src/core/openbsd/SDL_wscons_mouse.c",
    "SDL/src/core/os2/SDL_os2.c",
    "SDL/src/core/os2/geniconv/geniconv.c",
    "SDL/src/core/os2/geniconv/os2cp.c",
    "SDL/src/core/os2/geniconv/os2iconv.c",
    "SDL/src/core/os2/geniconv/sys2utf8.c",
    "SDL/src/core/os2/geniconv/test.c",
    "SDL/src/core/unix/SDL_poll.c",

    "SDL/src/file/n3ds/SDL_rwopsromfs.c",

    "SDL/src/filesystem/android/SDL_sysfilesystem.c",
    "SDL/src/filesystem/dummy/SDL_sysfilesystem.c",
    "SDL/src/filesystem/emscripten/SDL_sysfilesystem.c",
    "SDL/src/filesystem/n3ds/SDL_sysfilesystem.c",
    "SDL/src/filesystem/nacl/SDL_sysfilesystem.c",
    "SDL/src/filesystem/os2/SDL_sysfilesystem.c",
    "SDL/src/filesystem/ps2/SDL_sysfilesystem.c",
    "SDL/src/filesystem/psp/SDL_sysfilesystem.c",
    "SDL/src/filesystem/riscos/SDL_sysfilesystem.c",
    "SDL/src/filesystem/unix/SDL_sysfilesystem.c",
    "SDL/src/filesystem/vita/SDL_sysfilesystem.c",

    "SDL/src/haptic/android/SDL_syshaptic.c",
    "SDL/src/haptic/dummy/SDL_syshaptic.c",

    "SDL/src/hidapi/libusb/hid.c",
    "SDL/src/hidapi/mac/hid.c",

    "SDL/src/joystick/android/SDL_sysjoystick.c",
    "SDL/src/joystick/bsd/SDL_bsdjoystick.c",
    "SDL/src/joystick/dummy/SDL_sysjoystick.c",
    "SDL/src/joystick/emscripten/SDL_sysjoystick.c",
    "SDL/src/joystick/n3ds/SDL_sysjoystick.c",
    "SDL/src/joystick/os2/SDL_os2joystick.c",
    "SDL/src/joystick/ps2/SDL_sysjoystick.c",
    "SDL/src/joystick/psp/SDL_sysjoystick.c",
    "SDL/src/joystick/steam/SDL_steamcontroller.c",
    "SDL/src/joystick/vita/SDL_sysjoystick.c",

    "SDL/src/loadso/dummy/SDL_sysloadso.c",
    "SDL/src/loadso/os2/SDL_sysloadso.c",

    "SDL/src/locale/android/SDL_syslocale.c",
    "SDL/src/locale/dummy/SDL_syslocale.c",
    "SDL/src/locale/emscripten/SDL_syslocale.c",
    "SDL/src/locale/n3ds/SDL_syslocale.c",
    "SDL/src/locale/unix/SDL_syslocale.c",
    "SDL/src/locale/vita/SDL_syslocale.c",
    "SDL/src/locale/winrt/SDL_syslocale.c",

    "SDL/src/main/android/SDL_android_main.c",
    "SDL/src/main/dummy/SDL_dummy_main.c",
    "SDL/src/main/gdk/SDL_gdk_main.c",
    "SDL/src/main/n3ds/SDL_n3ds_main.c",
    "SDL/src/main/nacl/SDL_nacl_main.c",
    "SDL/src/main/ps2/SDL_ps2_main.c",
    "SDL/src/main/psp/SDL_psp_main.c",
    "SDL/src/main/uikit/SDL_uikit_main.c",

    "SDL/src/misc/android/SDL_sysurl.c",
    "SDL/src/misc/dummy/SDL_sysurl.c",
    "SDL/src/misc/emscripten/SDL_sysurl.c",
    "SDL/src/misc/riscos/SDL_sysurl.c",
    "SDL/src/misc/unix/SDL_sysurl.c",
    "SDL/src/misc/vita/SDL_sysurl.c",

    "SDL/src/power/android/SDL_syspower.c",
    "SDL/src/power/emscripten/SDL_syspower.c",
    "SDL/src/power/haiku/SDL_syspower.c",
    "SDL/src/power/n3ds/SDL_syspower.c",
    "SDL/src/power/psp/SDL_syspower.c",
    "SDL/src/power/vita/SDL_syspower.c",

    "SDL/src/sensor/android/SDL_androidsensor.c",
    "SDL/src/sensor/n3ds/SDL_n3dssensor.c",
    "SDL/src/sensor/vita/SDL_vitasensor.c",

    "SDL/src/test/SDL_test_assert.c",
    "SDL/src/test/SDL_test_common.c",
    "SDL/src/test/SDL_test_compare.c",
    "SDL/src/test/SDL_test_crc32.c",
    "SDL/src/test/SDL_test_font.c",
    "SDL/src/test/SDL_test_fuzzer.c",
    "SDL/src/test/SDL_test_harness.c",
    "SDL/src/test/SDL_test_imageBlit.c",
    "SDL/src/test/SDL_test_imageBlitBlend.c",
    "SDL/src/test/SDL_test_imageFace.c",
    "SDL/src/test/SDL_test_imagePrimitives.c",
    "SDL/src/test/SDL_test_imagePrimitivesBlend.c",
    "SDL/src/test/SDL_test_log.c",
    "SDL/src/test/SDL_test_md5.c",
    "SDL/src/test/SDL_test_memory.c",
    "SDL/src/test/SDL_test_random.c",

    "SDL/src/thread/n3ds/SDL_syscond.c",
    "SDL/src/thread/n3ds/SDL_sysmutex.c",
    "SDL/src/thread/n3ds/SDL_syssem.c",
    "SDL/src/thread/n3ds/SDL_systhread.c",
    "SDL/src/thread/os2/SDL_sysmutex.c",
    "SDL/src/thread/os2/SDL_syssem.c",
    "SDL/src/thread/os2/SDL_systhread.c",
    "SDL/src/thread/os2/SDL_systls.c",
    "SDL/src/thread/ps2/SDL_syssem.c",
    "SDL/src/thread/ps2/SDL_systhread.c",
    "SDL/src/thread/psp/SDL_syscond.c",
    "SDL/src/thread/psp/SDL_sysmutex.c",
    "SDL/src/thread/psp/SDL_syssem.c",
    "SDL/src/thread/psp/SDL_systhread.c",
    "SDL/src/thread/vita/SDL_syscond.c",
    "SDL/src/thread/vita/SDL_sysmutex.c",
    "SDL/src/thread/vita/SDL_syssem.c",
    "SDL/src/thread/vita/SDL_systhread.c",

    "SDL/src/timer/dummy/SDL_systimer.c",
    "SDL/src/timer/haiku/SDL_systimer.c",
    "SDL/src/timer/n3ds/SDL_systimer.c",
    "SDL/src/timer/os2/SDL_systimer.c",
    "SDL/src/timer/ps2/SDL_systimer.c",
    "SDL/src/timer/psp/SDL_systimer.c",
    "SDL/src/timer/vita/SDL_systimer.c",

    "SDL/src/video/android/SDL_androidclipboard.c",
    "SDL/src/video/android/SDL_androidevents.c",
    "SDL/src/video/android/SDL_androidgl.c",
    "SDL/src/video/android/SDL_androidkeyboard.c",
    "SDL/src/video/android/SDL_androidmessagebox.c",
    "SDL/src/video/android/SDL_androidmouse.c",
    "SDL/src/video/android/SDL_androidtouch.c",
    "SDL/src/video/android/SDL_androidvideo.c",
    "SDL/src/video/android/SDL_androidvulkan.c",
    "SDL/src/video/android/SDL_androidwindow.c",
    "SDL/src/video/directfb/SDL_DirectFB_WM.c",
    "SDL/src/video/directfb/SDL_DirectFB_dyn.c",
    "SDL/src/video/directfb/SDL_DirectFB_events.c",
    "SDL/src/video/directfb/SDL_DirectFB_modes.c",
    "SDL/src/video/directfb/SDL_DirectFB_mouse.c",
    "SDL/src/video/directfb/SDL_DirectFB_opengl.c",
    "SDL/src/video/directfb/SDL_DirectFB_render.c",
    "SDL/src/video/directfb/SDL_DirectFB_shape.c",
    "SDL/src/video/directfb/SDL_DirectFB_video.c",
    "SDL/src/video/directfb/SDL_DirectFB_vulkan.c",
    "SDL/src/video/directfb/SDL_DirectFB_window.c",
    "SDL/src/video/emscripten/SDL_emscriptenevents.c",
    "SDL/src/video/emscripten/SDL_emscriptenframebuffer.c",
    "SDL/src/video/emscripten/SDL_emscriptenmouse.c",
    "SDL/src/video/emscripten/SDL_emscriptenopengles.c",
    "SDL/src/video/emscripten/SDL_emscriptenvideo.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmdyn.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmevents.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmmouse.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmopengles.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmvideo.c",
    "SDL/src/video/kmsdrm/SDL_kmsdrmvulkan.c",
    "SDL/src/video/n3ds/SDL_n3dsevents.c",
    "SDL/src/video/n3ds/SDL_n3dsframebuffer.c",
    "SDL/src/video/n3ds/SDL_n3dsswkb.c",
    "SDL/src/video/n3ds/SDL_n3dstouch.c",
    "SDL/src/video/n3ds/SDL_n3dsvideo.c",
    "SDL/src/video/nacl/SDL_naclevents.c",
    "SDL/src/video/nacl/SDL_naclglue.c",
    "SDL/src/video/nacl/SDL_naclopengles.c",
    "SDL/src/video/nacl/SDL_naclvideo.c",
    "SDL/src/video/nacl/SDL_naclwindow.c",
    "SDL/src/video/offscreen/SDL_offscreenevents.c",
    "SDL/src/video/offscreen/SDL_offscreenframebuffer.c",
    "SDL/src/video/offscreen/SDL_offscreenopengles.c",
    "SDL/src/video/offscreen/SDL_offscreenvideo.c",
    "SDL/src/video/offscreen/SDL_offscreenwindow.c",
    "SDL/src/video/os2/SDL_os2dive.c",
    "SDL/src/video/os2/SDL_os2messagebox.c",
    "SDL/src/video/os2/SDL_os2mouse.c",
    "SDL/src/video/os2/SDL_os2util.c",
    "SDL/src/video/os2/SDL_os2video.c",
    "SDL/src/video/os2/SDL_os2vman.c",
    "SDL/src/video/pandora/SDL_pandora.c",
    "SDL/src/video/pandora/SDL_pandora_events.c",
    "SDL/src/video/ps2/SDL_ps2video.c",
    "SDL/src/video/psp/SDL_pspevents.c",
    "SDL/src/video/psp/SDL_pspgl.c",
    "SDL/src/video/psp/SDL_pspmouse.c",
    "SDL/src/video/psp/SDL_pspvideo.c",
    "SDL/src/video/qnx/gl.c",
    "SDL/src/video/qnx/keyboard.c",
    "SDL/src/video/qnx/video.c",
    "SDL/src/video/raspberry/SDL_rpievents.c",
    "SDL/src/video/raspberry/SDL_rpimouse.c",
    "SDL/src/video/raspberry/SDL_rpiopengles.c",
    "SDL/src/video/raspberry/SDL_rpivideo.c",
    "SDL/src/video/riscos/SDL_riscosevents.c",
    "SDL/src/video/riscos/SDL_riscosframebuffer.c",
    "SDL/src/video/riscos/SDL_riscosmessagebox.c",
    "SDL/src/video/riscos/SDL_riscosmodes.c",
    "SDL/src/video/riscos/SDL_riscosmouse.c",
    "SDL/src/video/riscos/SDL_riscosvideo.c",
    "SDL/src/video/riscos/SDL_riscoswindow.c",
    "SDL/src/video/vita/SDL_vitaframebuffer.c",
    "SDL/src/video/vita/SDL_vitagl_pvr.c",
    "SDL/src/video/vita/SDL_vitagles.c",
    "SDL/src/video/vita/SDL_vitagles_pvr.c",
    "SDL/src/video/vita/SDL_vitakeyboard.c",
    "SDL/src/video/vita/SDL_vitamessagebox.c",
    "SDL/src/video/vita/SDL_vitamouse.c",
    "SDL/src/video/vita/SDL_vitatouch.c",
    "SDL/src/video/vita/SDL_vitavideo.c",
    "SDL/src/video/vivante/SDL_vivanteopengles.c",
    "SDL/src/video/vivante/SDL_vivanteplatform.c",
    "SDL/src/video/vivante/SDL_vivantevideo.c",
    "SDL/src/video/vivante/SDL_vivantevulkan.c",

    "SDL/src/render/opengl/SDL_render_gl.c",
    "SDL/src/render/opengl/SDL_shaders_gl.c",
    "SDL/src/render/opengles/SDL_render_gles.c",
    "SDL/src/render/opengles2/SDL_render_gles2.c",
    "SDL/src/render/opengles2/SDL_shaders_gles2.c",
    "SDL/src/render/ps2/SDL_render_ps2.c",
    "SDL/src/render/psp/SDL_render_psp.c",
    "SDL/src/render/vitagxm/SDL_render_vita_gxm.c",
    "SDL/src/render/vitagxm/SDL_render_vita_gxm_memory.c",
    "SDL/src/render/vitagxm/SDL_render_vita_gxm_tools.c",
};

const linux_config_h_vals = .{
    .HAVE_GCC_ATOMICS = 1,
    // .HAVE_GCC_SYNC_LOCK_TEST_AND_SET = 0,
    .HAVE_LIBC = 1,
    .STDC_HEADERS = 1,
    .HAVE_ALLOCA_H = 1,
    .HAVE_CTYPE_H = 1,
    .HAVE_FLOAT_H = 1,
    .HAVE_ICONV_H = 1,
    .HAVE_INTTYPES_H = 1,
    .HAVE_LIMITS_H = 1,
    .HAVE_MALLOC_H = 1,
    .HAVE_MATH_H = 1,
    .HAVE_MEMORY_H = 1,
    .HAVE_SIGNAL_H = 1,
    .HAVE_STDARG_H = 1,
    .HAVE_STDDEF_H = 1,
    .HAVE_STDINT_H = 1,
    .HAVE_STDIO_H = 1,
    .HAVE_STDLIB_H = 1,
    .HAVE_STRINGS_H = 1,
    .HAVE_STRING_H = 1,
    .HAVE_SYS_TYPES_H = 1,
    .HAVE_WCHAR_H = 1,
    .HAVE_LINUX_INPUT_H = 1,
    // .HAVE_PTHREAD_NP_H = 0,
    .HAVE_LIBUNWIND_H = 1,
    .HAVE_DLOPEN = 1,
    .HAVE_MALLOC = 1,
    .HAVE_CALLOC = 1,
    .HAVE_REALLOC = 1,
    .HAVE_FREE = 1,
    .HAVE_ALLOCA = 1,
    .HAVE_GETENV = 1,
    .HAVE_SETENV = 1,
    .HAVE_PUTENV = 1,
    .HAVE_UNSETENV = 1,
    .HAVE_QSORT = 1,
    .HAVE_BSEARCH = 1,
    .HAVE_ABS = 1,
    .HAVE_BCOPY = 1,
    .HAVE_MEMSET = 1,
    .HAVE_MEMCP = 1,
    .HAVE_MEMMOVE = 1,
    .HAVE_MEMCMP = 1,
    .HAVE_WCSLEN = 1,
    // .HAVE_WCSLCPY = 0,
    // .HAVE_WCSLCAT = 0,
    // .HAVE__WCSDUP = 0,
    .HAVE_WCSDUP = 1,
    .HAVE_WCSSTR = 1,
    .HAVE_WCSCMP = 1,
    .HAVE_WCSNCMP = 1,
    .HAVE_WCSCASECMP = 1,
    // .HAVE__WCSICMP = 0,
    .HAVE_WCSNCASECMP = 1,
    // .HAVE__WCSNICMP = 0,
    .HAVE_STRLEN = 1,
    // .HAVE_STRLCPY = 0,
    // .HAVE_STRLCAT = 0,
    // .HAVE__STRREV = 0,
    // .HAVE__STRUPR = 0,
    // .HAVE__STRLWR = 0,
    .HAVE_INDEX = 1,
    .HAVE_RINDEX = 1,
    .HAVE_STRCHR = 1,
    .HAVE_STRSTR = 1,
    .HAVE_STRTOK_R = 1,
    // .HAVE_ITOA = 0,
    // .HAVE__LTOA = 0,
    // .HAVE__UITOA = 0,
    // .HAVE__ULTOA = 0,
    .HAVE_STRTOL = 1,
    .HAVE_STRTOUL = 1,
    // .HAVE__I64TOA = 0,
    // .HAVE__UI64TOA = 0,
    .HAVE_STRTOLL = 1,
    .HAVE_STRTOULL = 1,
    .HAVE_STRTOD = 1,
    .HAVE_ATOI = 1,
    .HAVE_ATOF = 1,
    .HAVE_STRCMP = 1,
    .HAVE_STRNCMP = 1,
    // .HAVE__STRICMP = 0,
    .HAVE_STRCASECMP = 1,
    // .HAVE__STRNICMP = 0,
    .HAVE_STRNCASECMP = 1,
    .HAVE_STRCASESTR = 1,
    .HAVE_SSCANF = 1,
    .HAVE_VCSSCANF = 1,
    .HAVE_VSNPRINTF = 1,
    .HAVE_M_PI = 1,
    .HAVE_ACOSF = 1,
    .HAVE_ASIN = 1,
    .HAVE_ASINF = 1,
    .HAVE_ATAN = 1,
    .HAVE_ATANF = 1,
    .HAVE_ATAN2 = 1,
    .HAVE_ATAN2F = 1,
    .HAVE_CUIL = 1,
    .HAVE_CEILF = 1,
    .HAVE_COPYSIGN = 1,
    .HAVE_COPYSIGNF = 1,
    .HAVE_COS = 1,
    .HAVE_COSF = 1,
    .HAVE_EXP = 1,
    .HAVE_EXPF = 1,
    .HAVE_FABS = 1,
    .HAVE_FABSF = 1,
    .HAVE_FLOOR = 1,
    .HAVE_FLOORF = 1,
    .HAVE_FMOD = 1,
    .HAVE_FMODF = 1,
    .HAVE_LOG = 1,
    .HAVE_LOG10 = 1,
    .HAVE_LOG10F = 1,
    .HAVE_LROUND = 1,
    .HAVE_LROUNDF = 1,
    .HAVE_POW = 1,
    .HAVE_POWF = 1,
    .HAVE_ROUND = 1,
    .HAVE_ROUNDF = 1,
    .HAVE_SCALBN = 1,
    .HAVE_SCALBNF = 1,
    .HAVE_SIN = 1,
    .HAVE_SINF = 1,
    .HAVE_SQRT = 1,
    .HAVE_SQRTF = 1,
    .HAVE_TAN = 1,
    .HAVE_TANF = 1,
    .HAVE_TRUNC = 1,
    .HAVE_TRUNCF = 1,
    .HAVE_FOPEN64 = 1,
    .HAVE_FSEEKO = 1,
    .HAVE_FSEEKO64 = 1,
    .HAVE_SIGACTION = 1,
    .HAVE_SA_SIGACTION = 1,
    .HAVE_SETJMP = 1,
    .HAVE_NANOSLEEP = 1,
    .HAVE_SYSCONF = 1,
    // .HAVE_SYSCTLBYNAME = 0,
    .HAVE_CLOCK_GETTIME = 1,
    // .HAVE_GETPAGESIZE = 0,
    .HAVE_MPROTECT = 1,
    .HAVE_ICONV = 1,
    .HAVE_PTHREAD_SETNAME_NP = 1,
    // .HAVE_PTHREAD_SET_NAME_NP = 0,
    .HAVE_SEM_TIMEDWAIT = 1,
    .HAVE_GETAUXVAL = 1,
    // .HAVE_ELF_AUX_INFO = 0,
    .HAVE_POLL = 1,
    .HAVE__EXIT = 1,
    // .HAVE_ALTIVEC_H = 0,
    .HAVE_DBUS_DBUS_H = 1,
    .HAVE_FCITX = 1,
    // .HAVE_IBUS_IBUS_H = 0,
    .HAVE_SYS_INOTIFY_H = 1,
    .HAVE_INOTIFY_INIT = 1,
    .HAVE_INOTIFY_INIT1 = 1,
    .HAVE_INOTIFY = 1,
    // .HAVE_LIBUSB = 0,
    .HAVE_O_CLOEXEC = 1,
    // .HAVE_IMMINTRIN_H = 0,
    .HAVE_LIBUDEV_H = 1,
    .HAVE_LIBSAMPLERATE_H = 1,
    .HAVE_LIBDECOR_H = 1,
    // .HAVE_D3D_H = 0,
    // .HAVE_D3D11_H = 0,
    // .HAVE_D3D12_H = 0,
    // .HAVE_DDRAW_H = 0,
    // .HAVE_DSOUND_H = 0,
    // .HAVE_DINPUT_H = 0,
    // .HAVE_XINPUT_H = 0,
    // .HAVE_WINDOWS_GAMING_INPUT_H = 0,
    // .HAVE_DXGI_H = 0,
    // .HAVE_MMDEVICEAPI_H = 0,
    // .HAVE_AUDIOCLIENT_H = 0,
    // .HAVE_TPCSHRD_H = 0,
    // .HAVE_SENSORSAPI_H = 0,
    // .HAVE_ROAPI_H = 0,
    // .HAVE_SHELLSCALINGAPI_H = 0,
    // .HAVE_XINPUT_GAMEPAD_EX = 0,
    // .HAVE_XINPUT_STATE_EX = 0,
    // .SDL_DEFAULT_ASSERT_LEVEL_CONFIGURED = 0,
    // .SDLDEFAULT_ASSERT_LEVEL = 0,
    // .SDL_ATOMIC_DISABLED = 0,
    // .SDL_AUDIO_DISABLED = 0,
    // .SDL_CPUINFO_DISABLED = 0,
    // .SDL_EVENTS_DISABLED = 0,
    // .SDL_FILE_DISABLED = 0,
    // .SDL_JOYSTICK_DISABLED = 0,
    // .SDL_HAPTIC_DISABLED = 0,
    // .SDL_HIDAPI_DISABLED = 0,
    // .SDL_SENSOR_DISABLED = 0,
    // .SDL_LOADSO_DISABLED = 0,
    // .SDL_RENDER_DISABLED = 0,
    // .SDL_THREADES_DISABLED = 0,
    // .SDL_TIMERS_DISABLED = 0,
    // .SDL_VIDEO_DISABLED = 0,
    // .SDL_POWER_DISABLED = 0,
    // .SDL_FILESYSTEM_DISABLED = 0,
    // .SDL_LOCALE_DISABLED = 0,
    // .SDL_MISC_DISABLED = 0,

    .SDL_AUDIO_DRIVER_ALSA = 1,
    .SDL_AUDIO_DRIVER_ALSA_DYNAMIC = "libasound.so.2",
    // .SDL_AUDIO_DRIVER_ANDROID = 0,
    // .SDL_AUDIO_DRIVER_OPENSLES = 0,
    // .SDL_AUDIO_DRIVER_AAUDIO = 0,
    // .SDL_AUDIO_DRIVER_ARTS = 0,
    // .SDL_AUDIO_DRIVER_ARTS_DYNAMIC = 0,
    // .SDL_AUDIO_DRIVER_COREAUDIO = 0,
    .SDL_AUDIO_DRIVER_DISK = 1,
    // .SDL_AUDIO_DRIVER_DSOUND = 0,
    .SDL_AUDIO_DRIVER_DUMMY = 1,
    // .SDL_AUDIO_DRIVER_EMSCRIPTEN = 0,
    // .SDL_AUDIO_DRIVER_ESD = 0,
    // .SDL_AUDIO_DRIVER_ESD_DYNAMIC = 0,
    // .SDL_AUDIO_DRIVER_FUSIONSOUND = 0,
    // .SDL_AUDIO_DRIVER_FUSIONSOUND_DYNAMIC = 0,
    // .SDL_AUDIO_DRIVER_HAIKU = 0,
    .SDL_AUDIO_DRIVER_JACK = 1,
    .SDL_AUDIO_DRIVER_JACK_DYNAMIC = "libjack.so.0",
    // .SDL_AUDIO_DRIVER_NAS = 0,
    // .SDL_AUDIO_DRIVER_NAS_DYNAMIC = 0,
    // .SDL_AUDIO_DRIVER_NETBSD = 0,
    .SDL_AUDIO_DRIVER_OSS = 1,
    // .SDL_AUDIO_DRIVER_PAUDIO = 0,
    .SDL_AUDIO_DRIVER_PIPEWIRE = 1,
    .SDL_AUDIO_DRIVER_PIPEWIRE_DYNAMIC = "libpipewire-0.3.so.0",
    .SDL_DRIVER_PULSEAUDIO = 1,
    .SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC = "libpulse-simple.so.0",
    // .SDL_AUDIO_DRIVER_QSA = 0,
    // .SDL_AUDIO_DRIVER_SNDIO = 0,
    // .SDL_AUDIO_DRIVER_SNDIO_DYNAMIC = 0,
    // .SDL_AUDIO_DRIVER_SUNAUDIO = 0,
    // .SDL_AUDIO_DRIVER_WASAPI = 0,
    // .SDL_AUDIO_DRIVER_WINMM = 0,
    // .SDL_AUDIO_DRIVER_OS2 = 0,
    // .SDL_AUDIO_DRIVER_VITA = 0,
    // .SDL_AUDIO_DRIVER_PSP = 0,
    // .SDL_AUDIO_DRIVER_PS2 = 0,
    // .SDL_AUDIO_DRIVER_N3DS = 0,

    .SDL_INPUT_LINUXEV = 1,
    .SDL_INPUT_LINUXKD = 1,
    // .SDL_INPUT_SBSDKBIO = 0,
    // .SDL_JOYSTICK_ANDROID = 0,
    // .SDL_JOYSTICK_HAIKU = 0,
    // .SDL_JOYSTICK_WGI = 0,
    // .SDL_JOYSTICK_DINPUT = 0,
    // .SDL_JOYSTICK_XINPUT = 0,
    // .SDL_JOYSTICK_DUMMY = 0,
    // .SDL_JOYSTICK_IOKIT = 0,
    // .SDL_JOYSTICK_MFI = 0,
    .SDL_JOYSTICK_LINUX = 1,
    // .SDL_JOYSTICK_OS2 = 0,
    // .SDL_JOYSTICK_USBHID = 0,
    // .SDL_HAVE_MACHINE_JOYSTICK_H = 0,
    // .SDL_JOYSTICK_HIDAPI = 0,
    // .SDL_JOYSTICK_RAWINPUT = 0,
    // .SDL_JOYSTICK_EMSCRIPTEN = 0,
    .SDL_JOYSTICK_VIRTUAL = 1,
    // .SDL_JOYSTICK_VITA = 0,
    // .SDL_JOYSTICK_PSP = 0,
    // .SDL_JOYSTICK_PS2 = 0,
    // .SDL_JOYSTICK_N3DS = 0,
    // .SDL_HAPTIC_DUMMY = 0,
    .SDL_HAPTIC_LINUX = 1,
    // .SDL_HAPTIC_IOKIT = 0,
    // .SDL_HAPTIC_DINPUT = 0,
    // .SDL_HAPTIC_XINPUT = 0,
    // .SDL_HAPTIC_ANDROID = 0,
    // .SDL_LIBUSB_DYNAMIC = 0,

    // .SDL_SENSOR_ANDROID = 0,
    // .SDL_SENSOR_COREMOTION = 0,
    // .SDL_SENSOR_WINDOWS = 0,
    .SDL_SENSOR_DUMMY = 1,
    // .SDL_SENSOR_VITA = 0,
    // .SDL_SENSOR_N3DS = 0,

    .SDL_LOADSO_DLOPEN = 1,
    // .SDL_LOADSO_DUMMY = 0,
    // .SDL_LOADSO_LDG = 0,
    // .SDL_LOADSO_WINDOWS = 0,
    // .SDL_LOADSOW_OS2 = 0,

    // .SDL_THREAD_GENERIC_COND_SUFFIX = 0,
    .SDL_THREAD_PTHREAD = 1,
    .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX = 1,
    // .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP = 0,
    // .SDL_THREAD_WINDOWS = 0,
    // .SDL_THREAD_OS2 = 0,
    // .SDL_THREAD_VITA = 0,
    // .SDL_THREAD_PSP = 0,
    // .SDL_THREAD_PS2 = 0,
    // .SDL_THREAD_N3DS = 0,

    // .SDL_TIMER_HAIKU = 0,
    // .SDL_TIMER_DUMMY = 0,
    .SDL_TIMER_UNIX = 1,
    // .SDL_TIMER_WINDOWS = 0,
    // .SDL_TIMER_OS2 = 0,
    // .SDL_TIMER_VITA = 0,
    // .SDL_TIMER_PSP = 0,
    // .SDL_TIMER_PS2 = 0,
    // .SDL_TIMER_N3DS = 0,

    // .SDL_VIDEO_DRIVER_ANDROID = 0,
    // .SDL_VIDEO_DRIVER_EMSCRIPTEN = 0,
    // .SDL_VIDEO_DRIVER_HAIKU = 0,
    // .SDL_VIDEO_DRIVER_COCOA = 0,
    // .SDL_VIDEO_DRIVER_UIKIT = 0,
    // .SDL_VIDEO_DRIVER_DIRECTFB = 0,
    // .SDL_VIDEO_DRIVER_DIRECTFB_DYNAMIC = 0,
    .SDL_VIDEO_DRIVER_DUMMY = 1,
    .SDL_VIDEO_DRIVER_OFFSCREEN = 1,
    // .SDL_VIDEO_DRIVER_WINDOWS = 0,
    // .SDL_VIDEO_DRIVES_WINRT = 0,
    .SDL_VIDEO_DRIVER_WAYLAND = 1,
    // .SDL_VIDEO_DRIVER_RPI = 0,
    // .SDL_VIDEO_DRIVER_VIVANTE = 0,
    // .SDL_VIDEO_DRIVER_VIVANTE_VDK = 0,
    // .SDL_VIDEO_DRIVER_OS2 = 0,
    // .SDL_VIDEO_DRIVER_QNX = 0,
    // .SDL_VIDEO_DRIVER_RISCOS = 0,
    // .SDL_VIDEO_DRIVER_PSP = 0,
    // .SDL_VIDEO_DRIVER_PS2 = 0,

    .SDL_VIDEO_DRIVER_KMSDRM = 1,
    .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC = "libdrm.so.2",
    .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC_GBM = "libgbm.so.1",

    .SDL_VIDEO_DRIVER_WAYLAND_QT_TOUCH = 1,
    .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC = "libwayland-client.so.0",
    .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL = "libwayland-egl.so.1",
    .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR = "libwayland-cursor.so.0",
    .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON = "libxkbcommon.so.0",
    .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR = "libdecor-0.so.0",

    .SDL_VIDEO_DRIVER_X11 = 1,
    .SDL_VIDEO_DRIVER_X11_DYNAMIC = "libx11.so.6",
    .SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT = "libXext.so.6",
    .SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR = "libXcursor.so.1",
    .SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 = "libXi.so.6",
    .SDL_VIDEO_DRIVER_X11_DYNAMIC_XFIXES = "libXfixes.so.3",
    .SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR = "libXrandr.so.2",
    .SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS = "libXss.so.1",
    .SDL_VIDEO_DRIVER_X11_XCURSOR = 1,
    .SDL_VIDEO_DRIVER_X11_XDBE = 1,
    .SDL_VIDEO_DRIVER_X11_XINPUT2 = 1,
    .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH = 1,
    .SDL_VIDEO_DRIVER_X11_XFIXES = 1,
    .SDL_VIDEO_DRIVER_X11_XRANDR = 1,
    .SDL_VIDEO_DRIVER_X11_XSCRNSAVER = 1,
    .SDL_VIDEO_DRIVER_X11_XSHAPE = 1,
    .SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS = 1,
    .SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM = 1,
    // .SDL_VIDEO_DRIVER_VITA = 0,
    // .SDL_VIDEO_DRIVER_N3DS = 0,

    // .SDL_VIDEO_RENDER_D3D = 0,
    // .SDL_VIDEO_RENDER_D3D11 = 0,
    // .SDL_VIDEO_RENDER_D3D12 = 0,
    .SDL_VIDEO_RENDER_OGL = 1,
    // .SDL_VIDEO_RENDER_OGL_ES = 0,
    .SDL_VIDEO_RENDER_OGL_ES2 = 1,
    // .SDL_VIDEO_RENDER_DIRECTFB = 0,
    // .SDL_VIDEO_RENDER_METAL = 0,
    // .SDL_VIDEO_RENDER_VITA_GXM = 0,
    // .SDL_VIDEO_RENDER_PS2 = 0,
    // .SDL_VIDEO_RENDER_PSP = 0,

    .SDL_VIDEO_OPENGL = 1,
    // .SDL_VIDEO_OPENGL_ES = 0,
    .SDL_VIDEO_OPENGL_ES2 = 1,
    // .SDL_VIDEO_OPENGL_BGL = 0,
    // .SDL_VIDEO_OPENGL_CGL = 0,
    .SDL_VIDEO_OPENGL_GLX = 1,
    // .SDL_VIDEO_OPENGL_WGL = 0,
    .SDL_VIDEO_OPENGL_EGL = 1,
    // .SDL_VIDEO_OPENGL_OSMESA = 0,
    // .SDL_VIDEO_OPENGL_OSMESA_DYNAMIC = 0,

    .SDL_VIDEO_VULKAN = 1,

    // .SDL_VIDEO_METAL = 0,

    // .SDL_POWER_ANDROID = 0,
    .SDL_POWER_LINUX = 1,
    // .SDL_POWER_WINDOWS = 0,
    // .SDL_POWER_WINRT = 0,
    // .SDL_POWER_MACOSX = 0,
    // .SDL_POWER_UIKIT = 0,
    // .SDL_POWER_HAIKU = 0,
    // .SDL_POWER_EMSCRIPTEN = 0,
    // .SDL_POWER_HARDWIRED = 0,
    // .SDL_POWER_VITA = 0,
    // .SDL_POWER_PSP = 0,
    // .SDL_POWER_N3DS = 0,

    // .SDL_FILESYSTEM_ANDROID = 0,
    // .SDL_FILESYSTEM_HAIKU = 0,
    // .SDL_FILESYSTEM_COCOA = 0,
    // .SDL_FILESYSTEM_DUMMY = 0,
    // .SDL_FILESYSTEM_RISCOS = 0,
    .SDL_FILESYSTEM_UNIX = 1,
    // .SDL_FILESYSTEM_WINDOWS = 0,
    // .SDL_FILESYSTEM_EMSCRIPTEN = 0,
    // .SDL_FILESYSTEM_OS2 = 0,
    // .SDL_FILESYSTEM_VITA = 0,
    // .SDL_FILESYSTEM_PSP = 0,
    // .SDL_FILESYSTEM_PS2 = 0,
    // .SDL_FILESYSTEM_N3DS = 0,

    // .SDL_MISC_DUMMY = 0,

    // .SDL_LOCALE_DUMMY = 0,

    // .SDL_ALTIVEC_BLITTERS = 0,
    // .SDL_ARM_SIMD_BLITTERS = 0,
    // .SDL_ARM_NEON_BLITTERS = 0,

    .DYNAPI_NEEDS_DLOPEN = 1,

    .SDL_LIBSAMPLERATE_DYNAMIC = "libsamplerate.so.0",
    // .SDL_USE_IME = 0,

    // .SDL_IPHONE_KEYBOARD = 0,
    // .SDL_IPHONE_LAUNCHSCREEN = 0,
    // .SDL_VIDEO_VITA_PIB = 0,
    // .SDL_VIDEO_VITA_PVR = 0,
    // .SDL_VIDEO_VITA_PVR_OGL = 0,
};
